import "./globals.css";


import type { NextMetaData } from "@typings/index";

import Footer from "@includes/Footer";
import NavBar from "@includes/NavBar";
import Container from "@includes/Container";



export const metadata: NextMetaData = {
  title: "Pianotes | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Container>
      <NavBar />
      {children}
      <Footer />
    </Container>
  );
}
